name: Download and Push Mods to Repo (with manual OptiFine)

on:
  workflow_dispatch:
  push:
   branches:
    - main

jobs:
  push_mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download Mods (excluding OptiFine)
        run: |
          mkdir -p mods
          curl -L -o mods/IceAndFire.jar "https://edge.forgecdn.net/files/4614/465/iceandfire-2.1.12-1.18.2.jar"
          curl -L -o mods/Create.jar "https://edge.forgecdn.net/files/4371/807/create-0.5.0i-1.18.2.jar"
          curl -L -o mods/JEI.jar "https://edge.forgecdn.net/files/3788/739/jei-1.18.2-9.7.0.195.jar"
          curl -L -o mods/SpartanWeaponry.jar "https://edge.forgecdn.net/files/5256/293/SpartanWeaponry-3.0.5-all.jar"
          curl -L -o mods/LycanitesMobs.jar "https://edge.forgecdn.net/files/2527/735/LycanitesMobsComplete%201.18.2.0.jar"
          curl -L -o mods/OptiForge.jar "https://edge.forgecdn.net/files/4329/838/OptiForge-MC1.18.2-0.5.8.jar"
          echo "::notice::OptiFine.jar is not downloaded. Please add it manually to mods/ before pushing."

      - name: Commit and Push all Mods (including manual OptiFine)
        run: |
          git add mods/
          git commit -m "Add mods including manually added OptiFine"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
